version: '3.9'

services:
  todolist-api:
    image: maksov-todolist-api:latest
    build:
      context: .
      dockerfile: Maksov.AwsTutorial.ToDoList.Api.Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "5296:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Host=postgres;Port=5432;Database=ToDoDb;Username=postgres;Password=yourpassword
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: ToDoDb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
